### ISSUE TITLE
A função está com o nome SingOut ao invés de SignOut

### ISSUE THREAD

**Issue by Cromaa** [rodrigorgtic/gameplay-nlw-together#4]
https://github.com/rodrigorgtic/gameplay-nlw-together/blob/c02d382f3094c9c3c40b34016848227a21a61467/src/components/Profile/index.tsx#L22

**Comment by rodrigorgtic** [comment]
Maravilha, bem observado. Muito obrigado, acabei de corrigir. 💜

**Comment by orodrigogo** [comment]
Maravilha, bem observado. Muito obrigado, acabei de corrigir. 💜
